---
hcp_dir: /scratch/tkuehn/ds004253
oasis_dir: /scratch/tkuehn/OASIS

# this configures the pybids grabber - create an entry for each type of input 
# you want to grab indexed by name of input dictionary for each input is 
# passed directly to pybids get()
# https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get
pybids_inputs:
  t1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

afids_inputs:
  afids:
    filters:
      suffix: afids
      extension: .fcsv
      space: T1w
      desc: groundtruth
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

train_proportion: 0.7

patch_size:
  - 6x6x6x0
ntrees:
  - 100
treedepth:
  - 50
usexyz:
  - true
spheresize:
  - 2

containers:
  afids_auto_train: /scratch/tkuehn/afids-auto-train.sif
  afids_auto_apply: /scratch/tkuehn/afids-auto-apply.sif
