---
lhscpd_dir: /home/tkuehn/Code/SNSX
output_dir: /home/tkuehn/Code/afids-auto-output

# this configures the pybids grabber - create an entry for each type of input 
# you want to grab indexed by name of input dictionary for each input is 
# passed directly to pybids get()
# https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get
pybids_inputs:
  test:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
      subject:
        - 106
        - 113
        - 122
        - 141
        - 163
    wildcards:
      - session
      - acquisition
      - task
      - run
  train:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
      subject:
        - 087
        - 093
        - 103
        - 107
        - 115
        - 116
        - 118
        - 120
        - 124
        - 125
        - 126
        - 127
        - 128
        - 131
        - 132
        - 133
        - 135
        - 136
        - 138
        - 139
        - 145
        - 146
        - 147
        - 148
        - 149
        - 150
        - 151
        - 152
        - 153
        - 156
        - 157
        - 158
        - 161
        - 162
        - 168
        - 106
        - 113
        - 122
        - 141
        - 163
    wildcards:
      - session
      - acquisition
      - task
      - run
afids_inputs:
  test:
    filters:
      suffix: afids
      extension: .fcsv
      space: T1w
      desc: groundtruth
      subject:
        - 106
        - 113
        - 122
        - 141
        - 163
    wildcards:
      - session
      - acquisition
      - task
      - run
  train:
    filters:
      suffix: afids
      extension: .fcsv
      space: T1w
      desc: groundtruth
      subject:
        - 087
        - 093
        - 103
        - 107
        - 115
        - 116
        - 118
        - 120
        - 124
        - 125
        - 126
        - 127
        - 128
        - 131
        - 132
        - 133
        - 135
        - 136
        - 138
        - 139
        - 145
        - 146
        - 147
        - 148
        - 149
        - 150
        - 151
        - 152
        - 153
        - 156
        - 157
        - 158
        - 161
        - 162
        - 168
        - 106
        - 113
        - 122
        - 141
        - 163
    wildcards:
      - session
      - acquisition
      - task
      - run

train_proportion: 0.7

patch_size:
  - 3x3x3x0
  - 6x6x6x0
  - 9x9x9x0
ntrees:
  - 50
  - 250
  - 500
treedepth:
  - 30
  - 40
  - 50
usexyz:
  - true
  - false
spheresize:
  - 2
  - 3
  - 4
