---
hcp_dir: /home/tkwork/Code/hcp
snsx_dir: /home/tkuehn/Code/SNSX
oasis_dir: /home/tkwork/Code/oasis
output_dir: /home/tkuehn/Code/afids-auto-output

# this configures the pybids grabber - create an entry for each type of input 
# you want to grab indexed by name of input dictionary for each input is 
# passed directly to pybids get()
# https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get
pybids_inputs:
  t1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

afids_inputs:
  afids:
    filters:
      suffix: afids
      extension: .fcsv
      space: T1w
      desc: groundtruth
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

train_proportion: 0.7

patch_size:
  - 3x3x3x0
  - 6x6x6x0
  - 9x9x9x0
ntrees:
  - 50
  - 250
  - 500
treedepth:
  - 30
  - 40
  - 50
usexyz:
  - true
  - false
spheresize:
  - 2
  - 3
  - 4
