---
hcp_dir: /home/tkuehn/Code/ds004253
snsx_dir: /home/tkuehn/Code/SNSX
oasis_dir: /home/tkuehn/Code/OASIS
output_dir: /home/tkuehn/Code/afids-auto-output

# this configures the pybids grabber - create an entry for each type of input 
# you want to grab indexed by name of input dictionary for each input is 
# passed directly to pybids get()
# https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get
pybids_inputs:
  t1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

afids_inputs:
  afids:
    filters:
      suffix: afids
      extension: .fcsv
      space: T1w
      desc: groundtruth
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

train_proportion: 0.7
